name: AmongUsPM%
authors: 
 - alvin0319
 - ZhaDev
main: alvin0319\AmongUs\AmongUs
version: 0.1.1
api: 5.0.0
website: https://github.com/alvin0319/AmongUs
softdepend: ["SimpleMapRenderer"]

permissions:
  amongus.command:
    default: true
  amongus.command.manage:
    default: op
